### ISSUE TITLE
'insert' not supported by KeyKit.fromKeyStroke

### ISSUE THREAD

**Issue by pekim** [romgrk/keykit#1]
`KeyKit.fromKeyStroke('insert')` results in an exception.
This is because `normalKeyStrokeRegex` does not include support for 'insert'.

It blows up in
`_ref1 = keystroke.match(this.normalKeyStrokeRegex), match = _ref1[0], key = _ref1[1], mod = _ref1[2];
`
because there is no match, and `_ref1` is `null`.

**Comment by romgrk** [comment]
Well noted. Thanks for reporting.

**Comment by romgrk** [comment]
Fixed by 3a3c9e263f8f4e6aac3676f0abd8b759c2e2f1b3.

**Comment by pekim** [comment]
Any thoughts on when you might publish a new version? (It would mean that I could remove a workaround for this issue from my code.)

**Comment by romgrk** [comment]
Working on it. However, this is reaaaaaally not production level, it's a real mess and I have no public API planned. 
I'll publish something this week, but use at your own risks.
